### ISSUE TITLE
No such image: drogon:latest

### ISSUE THREAD

**Issue by CyrusVorwald** [icon-community/drogon#5]
When initializing a project with samples, I get the following error:

`fatal     Failed to fetch boilerplate. Error: (HTTP code 404) no such container - No such image: drogon:latest`

See the full command log below

```
❯ yarn run drogon init
yarn run v1.22.17
$ node -p "'export const LIB_VERSION = ' + JSON.stringify(require('./package.json').version) + ';'" > src/version.ts
$ npx ts-node src/index.ts init
 _ .-') _  _  .-')                                             .-') _ ,---.
( (  OO) )( \( -O )                                           ( OO ) )|   |
 \     .'_ ,------.  .-'),-----.   ,----.     .-'),-----. ,--./ ,--,' |   |
 ,`'--..._)|   /`. '( OO'  .-.  ' '  .-./-') ( OO'  .-.  '|   \ |  |\ |   |
 |  |  \  '|  /  | |/   |  | |  | |  |_( O- )/   |  | |  ||    \|  | )|   |
 |  |   ' ||  |_.' |\_) |  |\|  | |  | .--, \\_) |  |\|  ||  .     |/ |  .'
 |  |   / :|  .  '.'  \ |  | |  |(|  | '. (_/  \ |  | |  ||  |\    |  `--'
 |  '--'  /|  |\  \    `'  '-'  ' |  '--'  |    `'  '-'  '|  | \   |  .--.
 `-------' `--' '--'     `-----'   `------'       `-----' `--'  `--'  '--'
✔ Name of the project … ibc-icon
✔ Do you want to initialize your Drogon project with samples? … no / yes
✔ Do you want to generate a keystore for this project? … no / yes
✔ Current working directory looks like a Drogon project. Do you want to overwrite all files? … no / yes
✔ Pick a boilerplate › Hello World
✨ Scaffolding done 🎉
✖  fatal     Failed to fetch boilerplate. Error: (HTTP code 404) no such container - No such image: drogon:latest
error Command failed with exit code 1.
```

**Comment by r3dsm0k3** [comment]
This should be fixed now. Thank you for raising the issue @CyrusVorwald

**Comment by CyrusVorwald** [comment]
I still have this issue with the same reproduction steps

**Comment by coconut-bunch** [comment]
you'll have to first do `drogon install` before you can do the init. `init` makes sure the necessary images are available locally.

**Comment by CyrusVorwald** [comment]
I was not able to do `drogon install`. See https://github.com/icon-community/drogon/issues/21 for more on that.

**Comment by FidelVe** [comment]
Im having the same issue,

I started running `npm install -g @icon-community/drogon` as per the instructions in the README.md.

after that I executed `drogon init` this is the result:

```
fidel@laptop:~/code/js/projects/icon-projects/drogon/01$ drogon init
 _ .-') _  _  .-')                                             .-') _ ,---. 
( (  OO) )( \( -O )                                           ( OO ) )|   | 
 \     .'_ ,------.  .-'),-----.   ,----.     .-'),-----. ,--./ ,--,' |   | 
 ,`'--..._)|   /`. '( OO'  .-.  ' '  .-./-') ( OO'  .-.  '|   \ |  |\ |   | 
 |  |  \  '|  /  | |/   |  | |  | |  |_( O- )/   |  | |  ||    \|  | )|   | 
 |  |   ' ||  |_.' |\_) |  |\|  | |  | .--, \\_) |  |\|  ||  .     |/ |  .' 
 |  |   / :|  .  '.'  \ |  | |  |(|  | '. (_/  \ |  | |  ||  |\    |  `--'  
 |  '--'  /|  |\  \    `'  '-'  ' |  '--'  |    `'  '-'  '|  | \   |  .--.  
 `-------' `--' '--'     `-----'   `------'       `-----' `--'  `--'  '--'  
✔ Name of the project … test-1
✔ Do you want to initialize your Drogon project with samples? … no / yes
✔ Do you want to generate a keystore for this project? … no / yes
/home/fidel/.nvm/versions/node/v18.13.0/lib/node_modules/@icon-community/drogon/node_modules/docker-modem/lib/modem.js:336
      var msg = new Error(
                ^

Error: (HTTP code 404) no such container - No such image: iconcommunity/drogon:latest 
    at /home/fidel/.nvm/versions/node/v18.13.0/lib/node_modules/@icon-community/drogon/node_modules/docker-modem/lib/modem.js:336:17
    at getCause (/home/fidel/.nvm/versions/node/v18.13.0/lib/node_modules/@icon-community/drogon/node_modules/docker-modem/lib/modem.js:366:7)
    at Modem.buildPayload (/home/fidel/.nvm/versions/node/v18.13.0/lib/node_modules/@icon-community/drogon/node_modules/docker-modem/lib/modem.js:335:5)
    at IncomingMessage.<anonymous> (/home/fidel/.nvm/versions/node/v18.13.0/lib/node_modules/@icon-community/drogon/node_modules/docker-modem/lib/modem.js:303:16)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such image: iconcommunity/drogon:latest' }
}

Node.js v18.13.0
```

**Comment by r3dsm0k3** [comment]
@CyrusVorwald I see. imho it it s a different issue. Since the pre-requisites are not met, (_in this case the docker images which needs to be pulled_), the `init` command is failing. 

Although this error is expected, the UX can be very much improved. I have added an enhancement ticket for this #23. 

@FidelVe , I am assuming that perhaps you did not do `drogon install` before doing the `init`. There was a gap in the documentation with regards to this, added a PR to address the documentation issue #22. 

Thank both of you for the bug reports. Im currently closing this issue because the documentation is updated now.
